sudo: require
dist: xenial
language: bash

# Montana Mendy runs lint (travis lint)

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

script:
  - bash gen_about.sh ./ about